- name: Run ansible.posix.patch Module
  become: "{{ misc__item._module.become | default(omit) }}"
  ansible.posix.patch:
    backup: "{{ misc__item.backup | default(omit) }}"
    basedir: "{{ misc__item.basedir | default(omit) }}"
    binary: "{{ misc__item.binary | default(omit) }}"
    dest: "{{ misc__item.dest | default(omit) }}"
    ignore_whitespace: "{{ misc__item.ignore_whitespace | default(omit) }}"
    remote_src: "{{ misc__item.remote_src | default(omit) }}"
    src: "{{ misc__item.src }}"
    state: "{{ misc__item.state | default(omit) }}"
    strip: "{{ misc__item.strip | default(omit) }}"
  delegate_to: "{{ misc__item._module.delegate_to | default(omit) }}"
  register: misc__ansible_posix_patch