---
- name: "Apply file or directory changes via systemd service module - Index: {{ __fm_itm_ind }}/{{ __fm_hnd_ind }}"
  become: true
  ansible.builtin.systemd_service: "{{ __fm_hnd |
    aybarsm.helper.only_with(__ansible.modules.ansible_builtin_systemd_service.params) }}"
  when: __fm_hnd._type | default('') == 'systemd_service'