ansible__role_enabled: true
ansible__manage_local_facts: true

ansible__local_fact_backup: true
ansible__local_facts_dir: "{{ (not lookup('config', 'DEFAULT_FACT_PATH')) | ternary('/etc/ansible/facts.d', lookup('config', 'DEFAULT_FACT_PATH')) }}"
ansible__local_fact_file: "{{ ansible__local_facts_dir }}/ansible.fact"
ansible__local_fact_template: etc/ansible/facts.d/ansible.json.fact.j2
ansible__local_fact_combine_recursive: true
ansible__local_fact_combine_list_merge: prepend

# ansible__local_facts_dir_owner: root
# ansible__local_facts_dir_group: root
# ansible__local_facts_dir_mode: '0755'