- name: Run ansible.builtin.copy Module
  become: "{{ misc__item._module.become | default(omit) }}"
  ansible.builtin.copy:
    attributes: "{{ misc__item.attributes | default(omit) }}"
    backup: "{{ misc__item.backup | default(omit) }}"
    checksum: "{{ misc__item.checksum | default(omit) }}"
    content: "{{ misc__item.content | default(omit) }}"
    decrypt: "{{ misc__item.decrypt | default(omit) }}"
    dest: "{{ misc__item.dest }}"
    directory_mode: "{{ misc__item.directory_mode | default(omit) }}"
    follow: "{{ misc__item.follow | default(omit) }}"
    force: "{{ misc__item.force | default(omit) }}"
    group: "{{ misc__item.group | default(omit) }}"
    local_follow: "{{ misc__item.local_follow | default(omit) }}"
    mode: "{{ misc__item.mode | default(omit) }}"
    owner: "{{ misc__item.owner | default(omit) }}"
    remote_src: "{{ misc__item.remote_src | default(omit) }}"
    selevel: "{{ misc__item.selevel | default(omit) }}"
    serole: "{{ misc__item.serole | default(omit) }}"
    setype: "{{ misc__item.setype | default(omit) }}"
    seuser: "{{ misc__item.seuser | default(omit) }}"
    src: "{{ misc__item.src | default(omit) }}"
    unsafe_writes: "{{ misc__item.unsafe_writes | default(omit) }}"
    validate: "{{ misc__item.validate | default(omit) }}"
  delegate_to: "{{ misc__item._module.delegate_to | default(omit) }}"
  register: misc__ansible_builtin_copy