---
- name: Handle file or directory changes
  block:
    - name: "Apply file or directory changes via systemd service module - Index: {{ __fm_itm_ind }}/{{ __fm_hnd_ind }}"
      become: true
      ansible.builtin.systemd_service: "{{ __fm_hnd |
        aybarsm.helper.only_with(__ansible.modules.ansible_builtin_systemd_service.params) }}"
      vars:
        __silent_on_skip: true
      when: __fm_hnd._type | default('') == 'systemd_service'

    - name: "Apply file or directory changes via service module - Index: {{ __fm_itm_ind }}/{{ __fm_hnd_ind }}"
      become: true
      ansible.builtin.service: "{{ __fm_hnd |
        aybarsm.helper.only_with(__ansible.modules.ansible_builtin_systemd_service.params) }}"
      vars:
        __silent_on_skip: true
      when: __fm_hnd._type | default('') == 'service'

    - name: "Apply file or directory changes via command module - Index: {{ __fm_itm_ind }}/{{ __fm_hnd_ind }}"
      become: "{{ __fm_hnd._become | default(true) }}"
      ansible.builtin.command: "{{ __fm_hnd |
        aybarsm.helper.only_with(__ansible.modules.ansible_builtin_command.params) }}"
      vars:
        __silent_on_skip: true
      when: __fm_hnd._type | default('') == 'command'
    
    - name: "Apply file or directory changes via Debug module - Index: {{ __fm_itm_ind }}/{{ __fm_hnd_ind }}"
      ansible.builtin.debug: 
        msg: "{{ __fm_hnd.msg }}"
      vars:
        __silent_on_skip: true
      when: __fm_hnd._type | default('') == 'debug'