---
- name: Include file and directory management tasks
  ansible.builtin.include_tasks: files.yml
  loop: "{{ file_mgr__items }}"
  loop_control:
    loop_var: __fm_itm
    index_var: __fm_itm_ind
  no_log: "{{ file_mgr__no_log }}"
  when:
    - file_mgr__role_enabled | default(false) | bool
    - file_mgr__items | length > 0