#ansible.posix.patch does not provide backup file and dest on return so we need to find it
- name: Get last backup file for patch
  ansible.builtin.find:
    paths: "{{ __fm_itm.dest | dirname }}"
    patterns: ["^{{ __fm_itm.dest | basename | regex_escape }}\\.~\\d+~$"]
    use_regex: true
  register: file_mgr__find_patch_backup_files
  vars:
    ansible_callback_diy_playbook_on_task_start_msg: "{{ omit if file_mgr__strict_safe and __fm_itm._type | default('') == 'patch' else '' }}"
    ansible_callback_diy_runner_on_skipped_msg: ''
  when:
    - file_mgr__strict_safe
    - __fm_itm._type | default('') == 'patch'
    - misc__ansible_posix_patch is changed

- name: Set Results Fact
  ansible.builtin.set_fact:
    file_mgr__all: "{{ file_mgr__all | aybarsm.helper.role_item_result(__fm_itm_ind, item_task) }}"
  vars:
    ansible_callback_diy_playbook_on_task_start_msg: "{{ omit if file_mgr__all[__fm_itm_ind]['_result'] is undefined else '' }}"
    ansible_callback_diy_runner_on_skipped_msg: ''
    patch_combine : "{{ {'backup_file': (file_mgr__find_patch_backup_files.files | map(attribute='path') | sort | last), 'dest': __fm_itm.dest}
      if file_mgr__find_patch_backup_files.files | default([]) | length > 0 else {} }}"
    item_task: "{{ misc__ansible_builtin_copy if __fm_itm._type | default('') == 'copy' else
      misc__ansible_builtin_file if __fm_itm._type | default('') == 'file' else
      misc__ansible_builtin_template if __fm_itm._type | default('') == 'template' else
      (dict(misc__ansible_posix_patch) | combine(patch_combine)) }}"
  register: file_mgr__set_result
  when: file_mgr__all[__fm_itm_ind]['_result'] is undefined
  