---
file_mgr__all: "{{ ((file_mgr__host | map('combine', {'entry__src': 'host'})) +
  (file_mgr__group | map('combine', {'entry__src': 'group'})) +
  (file_mgr__default | map('combine', {'entry__src': 'default'}))) |
  community.general.json_query('[?not_null(entry__module) && not_null(entry__keep, `true`)==`true` && not_null(entry__skip, `false`)==`false`]') |
  aybarsm.helper.all_except(['keep__entry', 'skip__entry']) }}"